#stages:
  # - build
  # - test
#  - deploy

# build:
#   stage: build
#   script:
#     - 

# test:
#   stage: test
#   script:
#     - 

#deploy-heroku:
#  image: ruby:latest
#  stage: deploy
#  before_script:
#    - gem install dpl
#  script:
#    - dpl --provider=heroku --app=$HEROKU_APP --api-key=$HEROKU_KEY
#  only:
#    - master
