stages:
  # - build
  # - test
  - deploy

# build:
#   stage: build
#   script:
#     - 

# test:
#   stage: test
#   script:
#     - 

deploy-vm:
  stage: deploy
  script:
    - fuser -k 80/tcp || true
    - /usr/bin/python3.10 -m venv env
    - source env/bin/activate
    - cd tarefaConnectFrontend/app
    - npm ci
    - npm install
    - npm run build
    - cd ../..
    - pip install --no-cache-dir --upgrade -r tarefaConnectBackend/requirements.txt
    - ./env/bin/fastapi run tarefaConnectBackend/backend/main.py --port 80 &> ~/runner.log &

#deploy-heroku:
#  image: ruby:latest
#  stage: deploy
#  before_script:
#    - gem install dpl
#  script:
#    - dpl --provider=heroku --app=$HEROKU_APP --api-key=$HEROKU_KEY
#  only:
#    - master
