stages:
  # - build
  # - test
  - deploy

# build:
#   stage: build
#   script:
#     - 

# test:
#   stage: test
#   script:
#     - 

deploy-vm:
  stage: deploy
  script:
    - fuser -k 80/tcp || true
    - cd tarefaConnectFrontend/app
    - npm run build
    - cd ../..
    - sudo /home/pc1822/drp_15/env/bin/fastapi run tarefaConnectBackend/backend/main.py --port 80 &

#deploy-heroku:
#  image: ruby:latest
#  stage: deploy
#  before_script:
#    - gem install dpl
#  script:
#    - dpl --provider=heroku --app=$HEROKU_APP --api-key=$HEROKU_KEY
#  only:
#    - master
